### ISSUE TITLE
CORS error when using with angular from localhost

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [thundermiracle/geocoder-free#80]
Access to fetch at 'https://www.google.com/search?gl=jp&tbm=map&q=....' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any idea why I'm getting this error?

**Comment by thundermiracle** [comment]
As you know, this is a cross domain data fetching problem. I tried to fix this by using [`JSONP`](https://en.wikipedia.org/wiki/JSONP), it worked.
But from your stack trace, it seems that JSONP is not working anymore. And as JSONP is not that safe, I recommend using this library in `server` side(nodejs) or using Google API in client side.

**Comment by mariomurrent-softwaresolutions** [comment]
Thanks for the hint ... yes it seems that it works in a nodejs environment.
